name: language_helper_mobile
description: Language Helper 2 - Mobile flashcard learning app with spaced repetition
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # FFI for calling Rust native code
  ffi: ^2.1.0

  # State management
  provider: ^6.1.0

  # Local storage
  path_provider: ^2.1.0
  path: ^1.8.3

  # UI components
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
